name: release

on:
  push:
    branches: [ master, cidev ]
  pull_request:
    branches: [ master, cidev ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.5.8
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.8
    - name: Build with bundler
      run: |
          gem install --no-rdoc --no-ri bundler
          bundle install --jobs 4 --retry 3 --deployment --without "development test"

