name: release

on:
  push:
    branches: [ master, cidev ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.5.8
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.8
    - name: Build with bundler
      run: |
          gem install --no-rdoc --no-ri bundler
          bundle install --jobs 4 --retry 3 --deployment --without "development test"
    - name: Zip
      run : |
        zip -r slowlog_check.zip ./*
    - name: Semantic Release
      id: semantic
      uses: cycjimmy/semantic-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        semantic_version: 17
      # You can specify specifying version range for the extra plugins if you prefer.
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
