name: Rspec and Release

on:
  push:
  pull_request:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby 3.3.4
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.4
    - name: Test with Rspec
      run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rspec
  release:
    if: github.event_name == 'push'
    needs: rspec
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby 3.3.4
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.4

    - name: Build with bundler
      run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --deployment --without "development test"

    - name: Zip
      run : |
        zip -r slowlog_check.zip ./*

    - name: Semantic Release
      id: semantic
      uses: cycjimmy/semantic-release-action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        semantic_version: 19
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git

    # Create a PR for CHANGELOG.md when a new release was published
    - name: Create PR for CHANGELOG
      if: steps.semantic.outputs.new_release_published == 'true'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: chore/changelog-v${{ steps.semantic.outputs.new_release_version }}
        commit-message: "chore(changelog): update for v${{ steps.semantic.outputs.new_release_version }}"
        title: "chore(changelog): update for v${{ steps.semantic.outputs.new_release_version }}"
        body: "Automated CHANGELOG update for v${{ steps.semantic.outputs.new_release_version }}"
        add-paths: |
          CHANGELOG.md
