name: Rspec and Release

on:
  push:
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby 3.3.4
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.4
    - name: Test with Rspec
      run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rspec
  release:
    if: github.event_name == 'push'
    needs: rspec
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 3.3.4
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.4
    - name: Build with bundler
      run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --deployment --without "development test"
    - name: Zip
      run : |
        zip -r slowlog_check.zip ./*
    - name: Semantic Release
      id: semantic
      uses: cycjimmy/semantic-release-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        semantic_version: 19
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git

