name: Rspec

on:
  push:
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.5.8
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.8
    - name: Test with Rspec
      run: |
          gem install --no-rdoc --no-ri bundler
          bundle install
          bundle exec rspec
