name: Build, Test, Zip

on:
  push:
    branches: [ master, cidev ]
  pull_request:
    branches: [ master, cidev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.5.8
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.8
    - name: Test with Rspec
      run: |
          gem install bundler
          bundle install
          bundle exec rspec --format documentation --color
